python train.py \
    --model_name_or_path zake7749/gemma-2-2b-it-chinese-kyara-dpo \
    --train_dataset_size 8000 \
    --dataset ./data/train.json \
    --source_max_len 360 \
    --target_max_len 256 \
    --bf16 \
    --output_dir ./output/4 \
    --per_device_train_batch_size 3 \
    --gradient_accumulation_steps 4 \
    --max_steps 500 \
    --save_steps 50 \
